name: On Release

on:
  push:
    #types: [created]

jobs:
  run_on_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script on release
        run: |
          echo "New release created: ${{ github.event.release.tag_name }}"
          # Run your desired script or command here
          pip install cyclonedx-bom
          cyclonedx-py -r -i ../logicmonitor_data_sdk_py/requirements.txt --format json -o sbom.jsom
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: sbom_report
          # A file, directory or wildcard pattern that describes what to upload
          path: sbom.json

