name: SBOM with tag release

on:
  push:
    tags:
      - 'v*'

jobs:
  run_on_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script on release
        run: |
          echo "New release created: ${{ github.event.release.tag_name }}"
          # Run your desired script or command here
          pip install cyclonedx-bom
          cyclonedx-py -r -i ../logicmonitor_data_sdk_py/requirements.txt --format json -o sbom.json
          ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: sbom_report
          # A file, directory or wildcard pattern that describes what to upload
          path: sbom.json
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          #body_path: sbom.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sbom.json
          asset_name: sbom.zip
          asset_content_type: application/gzip


